[package]
name = "wipac_datamove"
authors = ["Patrick Meade <pmeade@icecube.wisc.edu>"]
version = "0.0.1"
repository = "https://github.com/WIPACrepo/datamove"
description = "Modern data movement components"
edition = "2021"
publish = false

[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
oauth2 = "4.4.2"
