# Dockerfile-rpm

# use Rust to compile our crate
FROM almalinux:8.10 AS build
RUN dnf install -y epel-release && \
    dnf install -y \
        gcc \
        gcc-c++ \
        make \
        glibc-devel \
        openssl-devel \
        curl \
        git \
        pkg-config
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install cargo-generate-rpm
WORKDIR /app
COPY . .
RUN cargo build --release
RUN cargo generate-rpm
RUN ls -1 target/generate-rpm > target/RPM-NAME

# build the final container image
FROM almalinux:8.10 AS image
COPY --from=build /app/target/generate-rpm /rpm
COPY --from=build /app/target/RPM-NAME /rpm/RPM-NAME
