#!/usr/bin/env bash
# build-docker
# build a Debian 13 (trixie) container image for datamove

# get the first 12 characters of the commit hash from git as GIT_HASH
GIT_HASH="$(git log | head -1 | awk -e '{print $2}' | head -c 12)"

# build datamove, and tag it as datamove:GIT_HASH
docker buildx build $@ \
	--file Dockerfile-debian13 \
	--tag datamove:${GIT_HASH}-debian13 \
	.

# since we just built datamove, tag it again as datamove:latest
docker image tag datamove:${GIT_HASH} datamove:latest-debian13
