name: cargo build (release)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3.5.3

    - name: Install system dependencies
      run: |
        apt install musl-tools --yes

    - name: Compile a local package and all of its dependencies
      run: |
        cargo build --release --target=x86_64-unknown-linux-musl
