name: cargo outdated

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3.5.3

    - name: Check if dependencies are out of date
      run: |
        cargo install cargo-outdated
        cargo outdated --exit-code 1 --packages oauth2
